### ISSUE TITLE
IR and Ardour 5.4

### ISSUE THREAD

**Issue by funkmuscle** [Anchakor/ir.lv2#4]
hey first, is the project dead? I know the original is but hoping you're still doing fixes here.
This version every since Ardour 5 crashes Ardour. Even without using. What I mean is I'd load a session and load the plugin. without playing the project, I get these error messages:
`Skip explicit buffer seconds, preset in use
Skip explicit buffer seconds, preset in use
IR: fhash=87e9d78862c6c9d7 was not found in DB
IR: fhash=87e9d78862c6c9d7 was not found in DB
IR: fhash=87e9d78862c6c9d7 was not found in DB
Segmentation fault (core dumped)
`

 then Ardour crashes. remove IR from the project and no crash.
I'm using Arch64.

**Comment by SpotlightKid** [comment]
As also mentioned [here](https://aur.archlinux.org/packages/ir-lv2-git), I compiled a fresh ir-lv2 version from git and ardour from git as well and created a test session with a short loop played through the IR plugin and had no problems at all. The plugin loaded without errors, also when I saved the session and quit and restarted Ardour.

**Comment by funkmuscle** [comment]
yep I read that. I had to use the tarball found at KXStudio. works perfectly now. will try yours SpotlightKid again from AUR later as I see you did an update. thanx
