### ISSUE TITLE
release

### ISSUE THREAD

**Issue by dvzrv** [Anchakor/ir.lv2#8]
Could you tag a release, so package maintainers can create a versioned release of this software?
Thanks a lot for your work!

**Comment by Anchakor** [comment]
Created https://github.com/Anchakor/ir.lv2/releases/tag/v1.3.2-1, hope that helps

**Comment by dvzrv** [comment]
@Anchakor thanks!
However, I would advice against the "-1" part in a tag.
This is usually used downstream in the distros to distinguish different releases of a package builds (e.g. when the packager has to add a patch or move a file somewhere else to adhere to packaging standards).
1.3.2 or v1.3.2 is completely fine.

**Comment by Anchakor** [comment]
@dvzrv Yeah I was thinking about that, the issue is this is a fork with some additional patches, so if there were upstream version 1.3.3, I'd like there to be a clear relationship. I was thinking about v1.3.2.1 but that isn't semver AFAIK...
